apiVersion: v1
kind: Namespace
metadata:
  name: quest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest
  namespace: quest
spec:
  selector:
    matchLabels:
      app: quest
  replicas: 2
  template:
    metadata:
      labels:
        app: quest
    spec:
      containers:
        - name: quest
          image: XXXXXXXXXXXX.dkr.ecr.us-east-2.amazonaws.com/quest-web:latest
          ports:
            - containerPort: 3000
          env:
          - name: SECRET_WORD
            value: "TwelveFactor"
---
apiVersion: v1
kind: Service
metadata:
  name: quest
  namespace: quest
spec:
  selector:
    app: quest
  ports:
    - port: 3000
      targetPort: 3000
      name: 'quest'
  type: LoadBalancer